# -*- coding: utf-8 -*-
"""Gestor Agrícola Inteligente (Script Completo)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iM4BMNtXdghRxdtSZv6k150UdML4jEOf
"""

import streamlit as st
import pandas as pd
from datetime import datetime
import sqlite3
import plotly.express as px
from PIL import Image
import io
import folium
from streamlit_folium import st_folium

# --- Configuração da Página ---
st.set_page_config(
    page_title="Gestor Agrícola Inteligente",
    page_icon="🌾",
    layout="wide"
)

# --- Funções da Base de Dados (SQLite) ---

DB_FILE = "fazenda_completa.db"

def get_db_connection():
    """Cria e retorna uma conexão com a base de dados SQLite."""
    # check_same_thread=False é necessário para o Streamlit
    conn = sqlite3.connect(DB_FILE, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    """Inicializa a base de dados e cria a tabela de talhões se não existir."""
    conn = get_db_connection()
    cursor = conn.cursor()
    # Adicionando a nova coluna para o volume diário de irrigação
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS talhoes (
            id TEXT NOT NULL,
            data TEXT NOT NULL,
            season TEXT NOT NULL,
            cultura TEXT,
            solo TEXT,
            cobertura TEXT,
            irrigado BOOLEAN,
            volume_irrigacao REAL,
            volume_ml_diario REAL,
            aplicacoes_quimicas TEXT,
            latitude REAL,
            longitude REAL,
            custo_producao REAL,
            produtividade REAL,
            foto BLOB,
            PRIMARY KEY (id, data, season)
        )
    """)
    conn.commit()
    conn.close()

@st.cache_data(ttl=30) # Cache dos dados por 30 segundos
def load_all_data_from_db():
    """Carrega todos os registos da base de dados para um DataFrame."""
    conn = get_db_connection()
    query = "SELECT id, data, season, cultura, solo, cobertura, irrigado, volume_irrigacao, volume_ml_diario, aplicacoes_quimicas, latitude, longitude, custo_producao, produtividade FROM talhoes ORDER BY data DESC"
    df = pd.read_sql_query(query, conn)
    conn.close()
    if not df.empty:
        df['data'] = pd.to_datetime(df['data']).dt.date
    return df

def load_photo_from_db(talhao_id, data, season):
    """Carrega a foto de um registo específico."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT foto FROM talhoes WHERE id = ? AND data = ? AND season = ?", (talhao_id, data, season))
    result = cursor.fetchone()
    conn.close()
    return result['foto'] if result and result['foto'] else None

def save_data_to_db(data_dict):
    """Salva (insere ou atualiza) os dados de um talhão na base de dados."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO talhoes (id, data, season, cultura, solo, cobertura, irrigado, volume_irrigacao, volume_ml_diario, aplicacoes_quimicas, latitude, longitude, custo_producao, produtividade, foto)
        VALUES (:id, :data, :season, :cultura, :solo, :cobertura, :irrigado, :volume_irrigacao, :volume_ml_diario, :aplicacoes_quimicas, :latitude, :longitude, :custo_producao, :produtividade, :foto)
        ON CONFLICT(id, data, season) DO UPDATE SET
            cultura=excluded.cultura,
            solo=excluded.solo,
            cobertura=excluded.cobertura,
            irrigado=excluded.irrigado,
            volume_irrigacao=excluded.volume_irrigacao,
            volume_ml_diario=excluded.volume_ml_diario,
            aplicacoes_quimicas=excluded.aplicacoes_quimicas,
            latitude=excluded.latitude,
            longitude=excluded.longitude,
            custo_producao=excluded.custo_producao,
            produtividade=excluded.produtividade,
            foto=excluded.foto
    """, data_dict)
    conn.commit()
    conn.close()
    st.cache_data.clear()

# --- Inicialização da App ---
init_db()
all_data_df = load_all_data_from_db()

# --- BARRA LATERAL (SIDEBAR) ---
with st.sidebar:
    st.image("https://i.imgur.com/f69163D.png", width=100)
    st.title("Painel de Controlo")
    st.markdown("---")

    lista_talhoes = [f"Talhão {i}" for i in range(1, 101)]
    talhao_selecionado_nome = st.selectbox(
        "Selecione o Talhão:",
        options=lista_talhoes,
        key='talhao_selecionado'
    )

    latest_data_df = all_data_df[all_data_df['id'] == talhao_selecionado_nome]
    dados_atuais = None
    if not latest_data_df.empty:
        dados_atuais = latest_data_df.iloc[0].to_dict()
    else:
        dados_atuais = {
            "id": talhao_selecionado_nome, "data": datetime.now().date(), "season": "A",
            "cultura": "Nenhum", "solo": "", "cobertura": "", "irrigado": False,
            "volume_irrigacao": 0.0, "volume_ml_diario": 0.0, "aplicacoes_quimicas": "", "latitude": 0.0, "longitude": 0.0,
            "custo_producao": 0.0, "produtividade": 0.0
        }

# --- PÁGINA PRINCIPAL ---
st.title("🌾 Gestor Agrícola Inteligente")
st.markdown("---")

tab_titles = ["📝 Editar Talhão", "📄 Visualização Geral", "📊 Análise Comparativa", "🔎 Visualizar Talhão", "🗺️ Mapa Geográfico"]
tab1, tab2, tab3, tab4, tab5 = st.tabs(tab_titles)

with tab1:
    st.header(f"Editando Informações do **{talhao_selecionado_nome}**")
    with st.form(key="edit_form"):
        st.subheader("Informações Gerais e Agronómicas")
        col1, col2 = st.columns(2)
        with col1:
            data = st.date_input("Data do Registo:", value=dados_atuais["data"])
            season = st.selectbox("Season (Safra):", options=["A", "B"], index=["A", "B"].index(dados_atuais["season"]))
            cultura = st.selectbox("Tipo de Cultura:", options=["Soja", "Milho", "Algodão", "Nenhum"], index=["Soja", "Milho", "Algodão", "Nenhum"].index(dados_atuais["cultura"]))
            solo = st.text_input("Tipo de Solo:", value=dados_atuais["solo"])
        with col2:
            cobertura = st.text_input("Cobertura de Rotação:", value=dados_atuais["cobertura"])
            irrigado = st.checkbox("É Irrigado?", value=bool(dados_atuais.get("irrigado", False)))
            volume_irrigacao = 0.0
            volume_ml_diario = 0.0
            if irrigado:
                volume_irrigacao = st.number_input("Vazão Horária (m³/h):", value=float(dados_atuais.get("volume_irrigacao", 0.0)), min_value=0.0, format="%.2f")
                volume_ml_diario = st.number_input("Volume Diário (ml):", value=float(dados_atuais.get("volume_ml_diario", 0.0)), min_value=0.0, format="%.2f")

        st.subheader("Gestão Financeira e de Produção")
        col3, col4 = st.columns(2)
        with col3:
            custo_producao = st.number_input("Custo de Produção (R$/ha):", value=float(dados_atuais.get("custo_producao", 0.0)), min_value=0.0, format="%.2f")
        with col4:
            produtividade = st.number_input("Produtividade (sacos/ha):", value=float(dados_atuais.get("produtividade", 0.0)), min_value=0.0, format="%.2f")

        st.subheader("Localização e Registos")
        col5, col6 = st.columns(2)
        with col5:
            st.markdown("**Coordenadas Geográficas**")
            latitude = st.number_input("Latitude:", value=float(dados_atuais.get("latitude", 0.0)), format="%.6f")
            longitude = st.number_input("Longitude:", value=float(dados_atuais.get("longitude", 0.0)), format="%.6f")
        with col6:
            st.markdown("**Registo Fotográfico**")
            uploaded_photo = st.file_uploader("Carregar foto do talhão", type=["jpg", "jpeg", "png"])

        aplicacoes_quimicas = st.text_area("Aplicações Químicas:", value=dados_atuais["aplicacoes_quimicas"], height=100)

        submitted = st.form_submit_button("Salvar na Base de Dados")
        if submitted:
            photo_bytes = None
            if uploaded_photo is not None:
                photo_bytes = uploaded_photo.getvalue()

            dados_para_salvar = {
                "id": talhao_selecionado_nome, "data": data.strftime('%Y-%m-%d'), "season": season, "cultura": cultura,
                "solo": solo, "cobertura": cobertura, "irrigado": irrigado,
                "volume_irrigacao": volume_irrigacao, "volume_ml_diario": volume_ml_diario,
                "aplicacoes_quimicas": aplicacoes_quimicas, "latitude": latitude, "longitude": longitude,
                "custo_producao": custo_producao, "produtividade": produtividade,
                "foto": photo_bytes
            }
            save_data_to_db(dados_para_salvar)
            st.success(f"Dados do **{talhao_selecionado_nome}** para a data **{data.strftime('%d/%m/%Y')}** salvos com sucesso!")

            # --- LÓGICA PARA AVANÇAR PARA O PRÓXIMO TALHÃO ---
            # Encontra o índice do talhão atual
            current_index = lista_talhoes.index(talhao_selecionado_nome)
            # Calcula o índice do próximo talhão, voltando ao início se for o último
            next_index = (current_index + 1) % len(lista_talhoes)
            # Atualiza o estado da sessão para o seletor na barra lateral
            st.session_state.talhao_selecionado = lista_talhoes[next_index]

            st.rerun()

with tab2:
    st.header("Histórico Completo da Fazenda")
    if not all_data_df.empty:
        st.dataframe(all_data_df)
    else:
        st.info("A base de dados está vazia.")

with tab3:
    st.header("📊 Análise Comparativa")
    if all_data_df.empty or all_data_df['produtividade'].sum() == 0:
        st.warning("Não há dados de produção suficientes para gerar análises.")
    else:
        df_analise = all_data_df.drop_duplicates(subset=['id', 'season'], keep='first')

        st.subheader("Produtividade Média por Cultura e Safra")
        fig_prod = px.bar(df_analise, x='cultura', y='produtividade', color='season',
                          barmode='group', title="Produtividade Média (sacos/ha)",
                          labels={'produtividade': 'Produtividade Média', 'cultura': 'Cultura'})
        st.plotly_chart(fig_prod, use_container_width=True)

        st.subheader("Custo de Produção Médio por Cultura e Safra")
        fig_custo = px.bar(df_analise, x='cultura', y='custo_producao', color='season',
                           barmode='group', title="Custo de Produção Médio (R$/ha)",
                           labels={'custo_producao': 'Custo Médio', 'cultura': 'Cultura'})
        st.plotly_chart(fig_custo, use_container_width=True)

with tab4:
    st.header(f"Visualização Detalhada: **{talhao_selecionado_nome}**")
    if dados_atuais and not latest_data_df.empty:
        st.markdown(f"Exibindo o registo mais recente de **{dados_atuais['data'].strftime('%d/%m/%Y')}**.")
        st.markdown("---")

        col1, col2 = st.columns(2)
        with col1:
            st.subheader("📋 Informações Gerais")
            st.markdown(f"**🌿 Safra:** {dados_atuais['season']} | **🌱 Cultura:** {dados_atuais['cultura']}")
            st.metric(label="Produtividade", value=f"{dados_atuais.get('produtividade', 0):.2f} sc/ha")
            st.metric(label="Custo de Produção", value=f"R$ {dados_atuais.get('custo_producao', 0):.2f}/ha")

            with st.expander("Ver detalhes de irrigação e agronomia"):
                status_irrigacao = "Sim" if dados_atuais.get('irrigado') else "Não"
                st.markdown(f"**💧 Irrigado:** {status_irrigacao}")
                st.markdown(f"**⏱️ Vazão Horária:** {dados_atuais.get('volume_irrigacao', 0):.2f} m³/h")
                st.markdown(f"**💧 Volume Diário:** {dados_atuais.get('volume_ml_diario', 0):.2f} ml")
                st.markdown(f"**🟫 Solo:** {dados_atuais['solo']}")
                st.markdown(f"**🔄 Cobertura:** {dados_atuais['cobertura']}")

        with col2:
            st.subheader("📸 Registo Fotográfico")
            foto_db = load_photo_from_db(dados_atuais['id'], dados_atuais['data'].strftime('%Y-%m-%d'), dados_atuais['season'])
            if foto_db:
                st.image(Image.open(io.BytesIO(foto_db)), caption="Foto mais recente do talhão", use_column_width=True)
            else:
                st.info("Nenhuma foto registada para esta data.")

with tab5:
    st.header("🗺️ Mapa Geográfico Interativo")
    if all_data_df.empty:
        st.warning("Não há dados para exibir no mapa.")
    else:
        df_mapa = all_data_df.drop_duplicates(subset='id', keep='first')
        df_mapa = df_mapa[(df_mapa['latitude'].notna()) & (df_mapa['longitude'].notna()) & (df_mapa['latitude'] != 0.0) & (df_mapa['longitude'] != 0.0)]

        if df_mapa.empty:
            st.info("Nenhum talhão possui coordenadas geográficas válidas registadas.")
        else:
            # Define uma cor para cada cultura
            map_color = {'Soja': 'green', 'Milho': 'orange', 'Algodão': 'white', 'Nenhum': 'gray'}

            # Centraliza o mapa na média das coordenadas
            map_center = [df_mapa['latitude'].mean(), df_mapa['longitude'].mean()]
            m = folium.Map(location=map_center, zoom_start=13)

            # Adiciona as camadas de mapa (tiles)
            folium.TileLayer('https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}', attr='Google', name='Google Satélite').add_to(m)
            folium.TileLayer('OpenStreetMap', name='OpenStreetMap').add_to(m)

            # Adiciona os marcadores para cada talhão
            for idx, row in df_mapa.iterrows():
                popup_html = f"""
                <b>Talhão:</b> {row['id']}<br>
                <b>Cultura:</b> {row['cultura']}<br>
                <b>Produtividade:</b> {row['produtividade']:.2f} sc/ha
                """
                folium.Marker(
                    location=[row['latitude'], row['longitude']],
                    popup=folium.Popup(popup_html, max_width=200),
                    tooltip=row['id'],
                    icon=folium.Icon(color=map_color.get(row['cultura'], 'blue'))
                ).add_to(m)

            # Adiciona o controlo para alternar entre as camadas
            folium.LayerControl().add_to(m)

            # Exibe o mapa no Streamlit
            st_folium(m, width=725, height=500)